version: "3.3"
services:
  postgres_db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trader
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=trader" ]
      interval: 10s
      timeout: 5s
      retries: 5