spring:
  application:
    name: traderAPI

  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://postgres_db:5432/trader
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    continue-on-error: false
    initialization-mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop

---

spring:
  profiles: local
  application:
    name: traderAPI

  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://localhost:5432/trader
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    continue-on-error: false
    initialization-mode: always

